### ISSUE TITLE
Upvotes and Downvotes

### ISSUE THREAD

**Issue by 1407arjun** [1407arjun/linkhub#35]
On upvotes tab of the profile page, when a post is downvoted, it moves to the downvoted tab when switched but the upvote is still shown as the option on the post in the downvoted tab. It is resolved on refresh. Vice-versa in the downvoted to upvoted tab also.

**Comment by MrVSiK** [comment]
Could be an issue due to SSR

**Comment by 1407arjun** [comment]
> Could be an issue due to SSR

Oh okay. Do you know a fix for this? Or you may also patch it by making a pull request.
